### ISSUE TITLE
FindPeaks with Decimate done before

### ISSUE THREAD

**Issue by ThScEo** [sipss/GCIMS#23]
Hello,

**First of all, thank you for this useful package!**

- I encounter issue when trying to find peaks on decimated samples. 

- I can easily find peaks without using _decimate()_ (from spectrum or chromatogram), but when I use _decimate()_ function before, even if the shape of the curve seems to be identical to the non-decimated sample ( I checked that decimation did not modified the curve shape too strongly), _findPeaks_ function find nothing, or at least less peaks than on the non-decimated sample.

- I tried several factor for RT and DT axis, even with a factor = 2 for both axis, less peaks are found.

- **Could you explain me why? Maybe I am missing something!**

- Here is an example:
    - find Peaks on decimated sample with a factor 2 for both axis: 
![image](https://github.com/user-attachments/assets/0a658a1c-62e8-4534-b148-622926f4a789)

    - find Peaks on non-decimated sample : ![image](https://github.com/user-attachments/assets/e21b9dd0-cb58-48dd-8209-f64dcbfa6825)

    
Thank you

**Comment by zeehio** [comment]
Hi,

Apologies for having trouble with the peak detection.

I will do my best to reproduce the error and get it fixed. 

Could you please send me (or attach here) a small reproducible example just to make sure I can reproduce your issue (ideally including one sample)?.

Thanks!

**Comment by ThScEo** [comment]
Hello,

First of all, thank you for your answer, my apologies for the time it took to reply.

I havn’t encountered this problem anymore so I guess we can close this issue.

Thank you

**Comment by zeehio** [comment]
Thanks! Closing then! Have a nice day!
